version: '3'
services:
    php:
        build:
            dockerfile: ./.Docker/php/DockerFile
            args:
                WWWGROUP: '${WWWGROUP}'
        volumes:
            - './:/var/www'
        networks:
            - docker_network
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3307}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'docker_mysql:/var/lib/mysql'
        networks:
            - docker_network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    
    nginx:
        build:
          context: ./.Docker/nginx
        volumes_from:
          - php
        volumes:
          - ./.Docker/ssl:/etc/nginx/ssl
        ports:
          - "80:80"
          - "443:443"
        networks:
          - docker_network
        depends_on:
          - php
          - mysql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
          - 8080:80
        networks:
            - docker_network
        environment: 
          PMA_HOST: mysql
          PMA_USER: root
          PMA_PASSWORD: '${DB_PASSWORD}'
        depends_on:
            - mysql

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - docker_network
networks:
    docker_network:
        driver: bridge
volumes:
    docker_mysql:
        driver: local
