version: '3.5'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./.Docker/php/Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    external_links:
      - webserver:docker.local
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.Docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./.Docker/php/log:/var/log/php
    networks:
      - docker_network
  

  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./.Docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./.Docker/ssl:/etc/nginx/ssl
    networks:
      - docker_network
    depends_on:
      - app

#Docker Networks
networks:
  docker_network:
    name: docker_network
    driver: bridge

#Volumes
volumes:
  docker_data:
    driver: local
